# Numpy 복습진행 3/6

- try 행렬 합 구하기 => 반복문을 통해서!

In [17]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]
new_list = []
for i in range(len(matrix_1)):
    temp_list = []
    for j in range(len(matrix_1[i])):
        temp_list.append(matrix_1[i][j]+matrix_2[i][j])
    new_list.append(temp_list)
        
print(new_list)

[[6, 8], [10, 12]]


- 행렬 숫자 1씩 더하기

In [18]:
matrix_1 = [[1, 2], [3, 4]]
new_list = []
for i in range(len(matrix_1)):
    temp_list = []
    for j in range(len(matrix_1[i])):
        temp_list.append(matrix_1[i][j]+1)
    new_list.append(temp_list)
        
print(new_list)

[[2, 3], [4, 5]]


In [23]:
# Numpy로 행렬 합 구하기!
import numpy as np
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]
np.array(matrix_1)+np.array(matrix_2)

array([[ 6,  8],
       [10, 12]])

In [24]:
# Numpy로 숫자 1씩 더하기
matrix_1 = [[1, 2], [3, 4]]
np.array(matrix_1)+1


array([[2, 3],
       [4, 5]])

In [27]:
# 속도비교 => 넘파이가 성능이 좋다!! 
import time
size = 10000000
# list
x = list(range(size))
y = list(range(size))
start_time = time.time()
z = [x[i]+y[i] for i in range(size)]    
print('리스트 걸린시간', time.time() - start_time)
# adlist
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x+y
print('넘파이 걸린시간', time.time() - start_time)

리스트 걸린시간 2.4117777347564697
넘파이 걸린시간 0.22140765190124512


In [4]:
# Numpy에서 양의 정수 자료형
import numpy as np
x = np.uint(32)
print(x.dtype)
print(x)

uint32
32


In [7]:
# Numpy에서 배열 자료형
x = np.array([1, 2, 3, 4])
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [8]:
# Numpy에서 실수 자료형
x = np.float32([1, 2, 3, 4])
print(x.dtype)
print(x)

float32
[1. 2. 3. 4.]


In [9]:
# Numpy에서 데이터 타입 지정
x = np.array([1,2,3,4], dtype = np.float32)
print(x.dtype)
print(x)

float32
[1. 2. 3. 4.]


In [10]:
x= np.int32(x)
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [11]:
# 다차원 nparray
# 0차원
x = np.array(1)
print(x.shape) # 행렬구조
print(x.ndim) # 차원 확인
print(x.size) # 개수 확인

()
0
1


In [12]:
#1차원
x= np.array([1,2,3])
print(x.shape)
print(x.ndim)
print(x.size)

(3,)
1
3


In [13]:
# 2차원
x= np.array([[1,2],[3,4]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 2)
2
4


In [2]:
# np.arange() : 파이썬의 range()와 비슷!
import numpy as np
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
x= np.arange(10.0)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [6]:
x= np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [8]:
x= np.arange(1,10, 0.5)
print(x)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [11]:
x= np.arange(10,1, -0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [16]:
# np.linspace() : 균일한 간격으로 리스트 크기만큼의 리스트 생성
x = np.linspace(1,20,5)
print(x)
y= np.linspace(1,20,5, endpoint=False)
print(y)

[ 1.    5.75 10.5  15.25 20.  ]
[ 1.   4.8  8.6 12.4 16.2]


In [19]:
# np.reshape() : 데이터를 유지하면서 차원의 형태를 변경
# -1일 경우 자동으로 맞춰 생성
x = np.arange(9).reshape(3,3)
print(x)
y= np.arange(24).reshape(2,3,4)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [21]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [22]:
x = np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
# Slicing 
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
x= np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


In [30]:
# indexing & boolean indexing
x = np.arange(20).reshape(4,5)
print(x)
print(x[1][1], print([1,1]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[1, 1]
6 None


In [32]:
# random
# random.rand : 표준정규분포에서 5x5로 추출
print(np.random.rand(5,5))

[[0.26060195 0.12748814 0.82524563 0.31450429 0.55433502]
 [0.52151874 0.83695811 0.01866153 0.59065055 0.83784194]
 [0.43353452 0.62492136 0.99605691 0.17681389 0.3356345 ]
 [0.74457447 0.99568608 0.0553435  0.59872698 0.69173916]
 [0.60742718 0.25370319 0.61741151 0.86722739 0.78096956]]


In [34]:
# random.randint : 정수형 난수
# random.randint(a,b) : a와 b-1 사이의 임의의 정수
np.random.randint(1,10)

6

In [35]:
# 정수형 난수 크기 지정 => 개수 지정
np.random.randint(1,10,size=(5))

array([8, 3, 3, 2, 6])

In [36]:
# 모든 값이 1
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# 모든 값이 0
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
# 단위행렬
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
z= np.arange(10).reshape(2,5)
print(z)
z.ravel(order="F") # 옵션은 C와 F가능

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [51]:
# concatenate : 배열을 연결
x= np.arange(10).reshape(2,5)
y= np.arange(10).reshape(2,5)
print(np.concatenate([x,y],axis=0)) # 다음 행으로 연결
print(np.concatenate([x,y],axis=1)) # 다음 열로 연결

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


In [52]:
# split : 배열을 분해
x = np.arange(12)
np.split(x,4) # 배열을 4개로 쪼개

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [54]:
x = np.arange(16).reshape(4,4)
print(x)
np.split(x,2,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# 연산 및 집계 함수

In [58]:
x= np.arange(4).reshape(2,2)
y= np.arange(4).reshape(2,2)
print(x)
print(y)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [56]:
# 행렬곱
x.dot(y)

array([[ 2,  3],
       [ 6, 11]])

In [59]:
# 전치행렬
print(np.transpose(x))

[[0 2]
 [1 3]]


In [62]:
#역행렬
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [63]:
# 행렬식
np.linalg.det(x)

-2.0

In [69]:
# 평균
print(np.mean(x))
# 중간값
print(np.median(x))
# 표준편차
print(np.std(x))
# 분산
print(np.var(x))
# 합
print(np.sum(x))
# 축별 합 (열별, 행별)
print("=>",np.sum(x,axis =0))

1.5
1.5
1.118033988749895
1.25
6
=> [2 4]


In [70]:
#누적합
print(np.cumsum(x))
#누적곱
print(np.cumprod(x))
#최솟값
print(np.min(x))
#최솟값 위치
print(np.argmin(x))
#최댓값
print(np.max(x))
#최댓값 위치
print(np.argmax(x))


[0 1 3 6]
[0 0 0 0]
0
0
3
3


In [78]:
# 하나라도 참이어야 참
print(np.any(x>2))
# 모든 요소가 참이어야 참
print(np.all(x>4))
# 조건에 맞는 위치
print(np.where(x>3))
# 조건 , True일 경우, False 일 경우
print(x)
print(np.where(x>2, x, -100))

True
False
(array([], dtype=int64), array([], dtype=int64))
[[0 1]
 [2 3]]
[[-100 -100]
 [-100    3]]
